name: Xamarin

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:

    Build_Android:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET 3.1 + .NET v6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            3.1.x
        
      - name: Restore NuGet 
        run: |
          nuget restore
          
      - name: Build Android App
        run: |                    
          msbuild ./SaveImageToDatabaseSampleApp.Droid/SaveImageToDatabaseSampleApp.Droid.csproj /verbosity:normal /p:Configuration=Release
